### ISSUE TITLE
Windows - software trigger fails

### ISSUE THREAD

**Issue by IamSierraCharlie** [IamSierraCharlie/Contrastech_Python_SDK_for_Linux#5]
```
SoftTrigger getFrame fail! timeOut [1000]ms

Traceback (most recent call last):
  File "C:\Users\steve\PycharmProjects\Contrastech_Python_API_for_Linux\ImageGrabDemo.py", line 56, in <module>
    image = camera.grab_image()
  File "C:\Users\steve\PycharmProjects\Contrastech_Python_API_for_Linux\linuxCamsApi.py", line 359, in grab_image
    self.image_source.contents.release(self.image_source)
OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF
```

Fur investigation when I get some spare time

**Comment by IamSierraCharlie** [comment]
fixed in 2e21c6d6ac74c292135f4a8f19c2e4571df944d0
